<?php

echo '<a href="http://localhost:8000/step1">step 1</a>';
echo '<br>';
echo '<a href="http://localhost:8000/step2">step 2</a>';
echo '<br>';
echo '<a href="http://localhost:8000/step3">step 3</a>';
echo '<br>';
echo '<a href="http://localhost:8000/step4">step 4</a>';
echo '<br>';
echo '<a href="http://localhost:8000/step5">step 5</a>';
echo '<br>';
echo '<a href="http://localhost:8000/step6">step 6</a>';
echo '<br>';
echo '<a href="http://localhost:8000/step7">step 7</a>';
echo '<br>';
echo '<a href="http://localhost:8000/step8">step 8</a>';
echo '<br>';
echo '<a href="http://localhost:8000/step9">step 9</a>';
echo '<br>';
echo '<a href="http://localhost:8000/step10">step 10</a>';
echo '<br>';
echo '<a href="http://localhost:8000/step11">step 11</a>';
echo '<br>';
echo '<a href="http://localhost:8000/step12">step 12</a>';
echo '<br>';
echo '<a href="http://localhost:8000/step13">step 13</a>';
echo '<br>';
echo '<a href="http://localhost:8000/step14">step 14</a>';
echo '<br>';
echo '<a href="http://localhost:8000/step15">step 15</a>';
echo '<br>';
echo '<a href="http://localhost:8000/step16">step 16</a>';
